name: dino_run
description: "Game using Flame following DevKage tutorial"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  df_log: ^0.3.28
  flame: ^1.33.0
  flame_audio: ^2.11.11
  hive_ce: ^2.15.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gui/
    - assets/images/parallax_background/
    - assets/images/
    - assets/audio/
  fonts:
    - family: CrayonLibre
      fonts:
        - asset: assets/CrayonLibre-Regular.ttf
# OYE
# * FlameAudio defaults to look at /assets/audio and it's FAWLTY to pick elsewhere
# https://flutter.dev/to/resolution-aware-images
# https://flutter.dev/to/asset-from-package
# see https://flutter.dev/to/font-from-package
